-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 19:50:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema campeonato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campeonato` DEFAULT CHARACTER SET utf8 ;
USE `campeonato` ;

-- -----------------------------------------------------
-- Table `campeonato`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campeonato`.`jogador` (
  `id_jogador` INT NOT NULL AUTO_INCREMENT,
  `nome_jogador` VARCHAR(45) NOT NULL,
  `altura_jogador` DECIMAL(10,2) NULL,
  `dt_nasc_jogador` DATE NULL,
  `categoria_jogador` VARCHAR(45) NULL,
  `genero_jogador` VARCHAR(45) NULL,
  `posicao_jogador` VARCHAR(45) NULL,
  `numero_jogador` CHAR(3) NULL,
  PRIMARY KEY (`id_jogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campeonato`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campeonato`.`equipe` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome_equipe` VARCHAR(45) NOT NULL,
  `estado_equipe` VARCHAR(45) NULL,
  `cidade_equipe` VARCHAR(45) NULL,
  `ginasio_equipe` VARCHAR(45) NULL,
  `jogador_id_jogador` INT NOT NULL,
  PRIMARY KEY (`id_equipe`, `jogador_id_jogador`),
  INDEX `fk_equipe_jogador_idx` (`jogador_id_jogador` ASC) ,
  CONSTRAINT `fk_equipe_jogador`
    FOREIGN KEY (`jogador_id_jogador`)
    REFERENCES `campeonato`.`jogador` (`id_jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
